# Generated by Django 5.0.2 on 2024-02-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorcomanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='excluida',
            field=models.BooleanField(default=False),
        ),
    ]
